# Generated by Django 2.1.5 on 2019-02-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190228_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='a_myself',
            new_name='about_myself',
        ),
    ]
