# Generated by Django 2.2 on 2019-04-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190405_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
