# Generated by Django 2.2 on 2019-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190408_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
