# Generated by Django 2.2 on 2019-04-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190418_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=128, null=True),
        ),
    ]
