# Generated by Django 2.1.5 on 2019-02-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_pub',
            new_name='date_posted',
        ),
    ]
