# Generated by Django 2.2 on 2019-04-23 13:22

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190423_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
