# Generated by Django 2.1.5 on 2019-03-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date_posted',
        ),
    ]
